baseURL = 'https://sivalabsacademy.github.io'
languageCode = 'en-us'
title = 'SivaLabs Academy'

theme = "freelancer"
summaryLength=40
paginate=9
pluralizeListTitles=false

[params]
  tagLine = "Learn from Real World Hands-on Experience"
  homeCourses = 10

  aboutLeft = "I work full time as a Java Developer, however I love to tinker and build things. So I also spend a lot of time out of work coding as well."
  aboutRight = "I've created this little slice of the internet, to keep track of what I do, and give me something to look back on from time to time."

[params.location]
  lineOne = "Hyderabad"
  lineTwo = "India"

#[params.sbform]
#      token = ""

[[params.social]]
    icon      = "twitter" # icon name without the 'fa-'
    icon_pack = "fab"
    url       = "https://twitter.com/sivalabs"

[[params.social]]
    icon      = "github" # icon name without the 'fa-'
    icon_pack = "fab"
    url       = "https://github.com/sivaprasadreddy"

[[params.social]]
    icon      = "youtube" # icon name without the 'fa-'
    icon_pack = "fab"
    url       = "https://youtube.com/sivalabs"

[[params.social]]
    icon      = "linkedin" # icon name without the 'fa-'
    icon_pack = "fab"
    url       = "https://www.linkedin.com/in/ksivaprasadreddy/"



[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10

[markup]
  [markup.highlight]
    margin = 10
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'friendly'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
     [outputFormats.RSS]
         mediaType = "application/rss+xml"
         baseName = "feed"
